<?php
/**
 * moosh2 — Moodle Shell
 *
 * @copyright  2012 onwards Tomasz Muras
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace Moosh2\Command\Event;

use Moosh2\Command\BaseHandler;
use Moosh2\Output\VerboseLogger;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * event:discover implementation for Moodle 5.1.
 */
class EventDiscover51Handler extends BaseHandler
{
    public function configureCommand(Command $command): void
    {
        $command
            ->addArgument('path', InputArgument::REQUIRED, 'Path to the Moodle source directory');
    }

    public function handle(InputInterface $input, OutputInterface $output): int
    {
        $verbose = new VerboseLogger($output);

        $moodlePath = rtrim($input->getArgument('path'), '/');

        if (!is_dir($moodlePath)) {
            $output->writeln('<error>Directory not found: ' . $moodlePath . '</error>');
            return Command::FAILURE;
        }

        $verbose->step('Scanning for event classes in ' . $moodlePath);

        $eventFiles = $this->findEventFiles($moodlePath);
        $verbose->detail('Found PHP files in event directories', (string) count($eventFiles));

        $eventNames = [];
        $skipped = 0;

        foreach ($eventFiles as $filePath) {
            $contents = file_get_contents($filePath);

            // Extract namespace.
            if (!preg_match('/^namespace\s+(.+?)\s*;/m', $contents, $nsMatch)) {
                $skipped++;
                continue;
            }
            $namespace = $nsMatch[1];

            // Extract class name — must extend something (filters out observers, base, manager).
            if (!preg_match('/^class\s+(\w+)\s+extends\s+/m', $contents, $classMatch)) {
                $skipped++;
                continue;
            }
            $className = $classMatch[1];

            // Skip abstract classes.
            if (preg_match('/^abstract\s+class\s+' . preg_quote($className, '/') . '/m', $contents)) {
                $skipped++;
                continue;
            }

            $eventName = '\\' . $namespace . '\\' . $className;
            $eventNames[] = $eventName;
        }

        $verbose->detail('Skipped non-event files', (string) $skipped);

        // Sort alphabetically and assign sequential IDs.
        sort($eventNames);
        $eventMap = [];
        $id = 1;
        foreach ($eventNames as $name) {
            $eventMap[$name] = $id++;
        }

        $verbose->done('Discovered ' . count($eventMap) . ' event classes');

        // Write the event map file.
        $outputPath = dirname(__DIR__, 2) . '/Data/event_map.php';
        $this->writeEventMap($outputPath, $eventMap);

        $verbose->done('Wrote event map to ' . $outputPath);
        $output->writeln('Discovered ' . count($eventMap) . ' events, wrote to src/Data/event_map.php');

        return Command::SUCCESS;
    }

    private function findEventFiles(string $basePath): array
    {
        $files = [];
        $iterator = new \RecursiveIteratorIterator(
            new \RecursiveDirectoryIterator($basePath, \RecursiveDirectoryIterator::SKIP_DOTS),
        );

        foreach ($iterator as $file) {
            if ($file->getExtension() !== 'php') {
                continue;
            }

            $path = $file->getPathname();

            // Match */classes/event/*.php but not deeper subdirectories like */classes/event/observer/*.php
            if (preg_match('#/classes/event/[^/]+\.php$#', $path)) {
                $files[] = $path;
            }
        }

        sort($files);
        return $files;
    }

    private function writeEventMap(string $path, array $eventMap): void
    {
        $lines = ["<?php\n"];
        $lines[] = "/**\n";
        $lines[] = " * Auto-generated by moosh event:discover.\n";
        $lines[] = " * Maps Moodle event names to numeric IDs for compact log export.\n";
        $lines[] = " *\n";
        $lines[] = " * @generated\n";
        $lines[] = " */\n";
        $lines[] = "return [\n";

        foreach ($eventMap as $name => $id) {
            $escaped = addcslashes($name, "'\\");
            $lines[] = "    '$escaped' => $id,\n";
        }

        $lines[] = "];\n";

        file_put_contents($path, implode('', $lines));
    }
}
